
### POST para insertar un  tarifasProfesional
POST http://localhost:3001/tarifasProfesional/insertarTarifaProfesional
Content-Type: application/json

{
  "profesional_id": 1,
  "servicio_id": 1,
  "precio": 25000,
  "duracion_min": 30
}


### POST para actualizar un  tarifasProfesional
POST http://localhost:3001/tarifasProfesional/actualizarTarifaProfesional
Content-Type: application/json

{
  "profesional_id": 1,
  "servicio_id": 1,
  "precio": 30000,
  "duracion_min": 45,
  "id_tarifaProfesional": 1
}



### POST para seleccionar un tarifasProfesional
POST http://localhost:3001/tarifasProfesional/seleccionarTarifaProfesional
Content-Type: application/json

{
  "id_tarifaProfesional": 3
}


### POST para eliminar un tarifasProfesional
POST http://localhost:3001/tarifasProfesional/eliminarTarifaProfesional
Content-Type: application/json

{
  "id_tarifaProfesional": 3
}



### GET para seleccionara todos los tarifasProfesional
GET http://localhost:3001/tarifasProfesional/seleccionarTodasTarifasProfesionales
Content-Type: application/json




### GET para seleccionara todos los tarifasProfesional
GET http://localhost:3001/tarifasProfesional/seleccionarTodasTarifasConNombres
Content-Type: application/json